ALTER TABLE crystals ADD COLUMN IF NOT EXISTS visual_description text DEFAULT 'raw gemstone mineral';
ALTER TABLE herbs ADD COLUMN IF NOT EXISTS visual_description text DEFAULT 'medicinal botanical herb';

UPDATE crystals SET visual_description = 'golden yellow transparent citrine quartz gemstone' WHERE name = 'Citrine';
UPDATE crystals SET visual_description = 'shiny black volcanic glass obsidian stone' WHERE name = 'Black Obsidian';
UPDATE crystals SET visual_description = 'clear transparent pointed quartz crystal' WHERE name = 'Clear Quartz';
UPDATE crystals SET visual_description = 'soft pink translucent rose quartz mineral' WHERE name = 'Rose Quartz';
UPDATE crystals SET visual_description = 'banded orange and red carnelian chalcedony' WHERE name = 'Carnelian';
UPDATE crystals SET visual_description = 'deep blue lapis lazuli stone with gold flecks' WHERE name = 'Lapis Lazuli';
UPDATE crystals SET visual_description = 'striped gold and brown tigers eye gemstone' WHERE name = 'Tigers Eye';
UPDATE crystals SET visual_description = 'iridescent labradorite stone blue green flash' WHERE name = 'Labradorite';
UPDATE crystals SET visual_description = 'opaque green aventurine quartz crystal' WHERE name = 'Green Aventurine';
UPDATE crystals SET visual_description = 'milky white translucent moonstone mineral' WHERE name = 'Moonstone';
UPDATE crystals SET visual_description = 'metallic silver hematite stone mineral' WHERE name = 'Hematite';
UPDATE crystals SET visual_description = 'opaque brick red jasper stone' WHERE name = 'Red Jasper';
UPDATE crystals SET visual_description = 'fibrous white satin spar selenite crystal' WHERE name = 'Selenite';
UPDATE crystals SET visual_description = 'deep green malachite with banded patterns' WHERE name = 'Malachite';
UPDATE crystals SET visual_description = 'smoky grey translucent quartz crystal' WHERE name = 'Smoky Quartz';
UPDATE crystals SET visual_description = 'yellow and black bumblebee jasper stone' WHERE name = 'Bumblebee Jasper';
UPDATE crystals SET visual_description = 'raw black tourmaline needle crystal' WHERE name = 'Black Tourmaline';
UPDATE herbs SET visual_description = 'purple lavender flowers in a field' WHERE name = 'Lavender';
UPDATE herbs SET visual_description = 'white sage smudge stick bundle' WHERE name = 'White Sage';
UPDATE herbs SET visual_description = 'fresh rosemary sprigs on wooden background' WHERE name = 'Rosemary';
UPDATE herbs SET visual_description = 'vibrant peppermint green leaves' WHERE name = 'Peppermint';
UPDATE herbs SET visual_description = 'yellow chamomile daisy flowers' WHERE name = 'Chamomile';
UPDATE herbs SET visual_description = 'cinnamon bark sticks tied with twine' WHERE name = 'Cinnamon';
UPDATE herbs SET visual_description = 'silvery green mugwort herb plant' WHERE name = 'Mugwort';
UPDATE herbs SET visual_description = 'bright orange calendula petals' WHERE name = 'Calendula';
UPDATE herbs SET visual_description = 'stinging nettle green plant leaves' WHERE name = 'Nettle';
UPDATE herbs SET visual_description = 'dried bay leaves spice' WHERE name = 'Bay Laurel';
UPDATE herbs SET visual_description = 'thyme herb sprigs' WHERE name = 'Thyme';
UPDATE herbs SET visual_description = 'red rose buds and petals' WHERE name = 'Rose';
UPDATE herbs SET visual_description = 'dandelion yellow flower and green leaves' WHERE name = 'Dandelion';
UPDATE herbs SET visual_description = 'elderberry dark purple berries' WHERE name = 'Elderberry';
UPDATE herbs SET visual_description = 'green lemon balm herb leaves' WHERE name = 'Lemon Balm';
UPDATE herbs SET visual_description = 'valerian root dried herb' WHERE name = 'Valerian';